spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/dsdeliver
        username: postgres
        password: pass
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
#                hbm2ddl:
#                    delimiter: ;
                jdbc:
                    lob:
                        non_contextual_creation: true
#            javax:
#                persistence:
#                    schema-generation:
#                        create-source: metadata
#                        scripts:
#                            action: create
#                            create-target: create.sql
